# Generated by Django 3.1.6 on 2021-02-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=60)),
                ('price', models.FloatField(default=0)),
                ('publisher', models.CharField(max_length=120)),
            ],
        ),
    ]
